### ISSUE TITLE
Add a code style tab to the solution detail view

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#157]

**Comment by freakyblue** [comment]
Which information should be displayed in this tab?

**Comment by martinmo** [comment]
FindBugs is a static analyzer for Java bytecode and detects certain bug patterns (see http://findbugs.sourceforge.net/). You can think of it as stricter and sometimes more intelligent compiler warnings and they can be displayed this way. But I think we should wait with this issue until #192 is finished. It would be ideal to overlay the FindBugs warnings with the source code listings.

The Docker image also needs to be setup to produce a FindBugs XML:withMessages report in addition to the JUnit reports (we use ant, so http://findbugs.sourceforge.net/manual/anttask.html applies). I couldn't find an XML schema or similar documentation of that format, but I doubt it will change or be very difficult to parse with Python. For example, our JUnit XML report parser was really straightforward to implement using the `[defused]xml.etree` package from the standard library.

**Comment by martinmo** [comment]
As a starting point for the Checkstyle config, take a look at http://ceur-ws.org/Vol-2066/isee2018paper06.pdf and the referenced Github repo.

**Comment by PhilippMatthes** [comment]
@martinmo I checked out the Checkstyle config, as well as the PMD config referred to in the paper. Unfortunately, the Checkstyle config has issues, so it cannot be started. The PMD config on the other hand can be started, but has many deprecation warnings. So for convenience purposes, I am going to use other configurations until the system is implemented. Then afterwards I will optimize them.

**Comment by martinmo** [comment]
Okay. Out of curiosity, what kind of issues does the Checkstyle config have?

**Comment by PhilippMatthes** [comment]
The checkstyle config was somehow malformed, so it could not be executed. It seemed to be none of my mistakes, because a simple replacement of the config solved the issue. Unfortunately, I was not able to locate the issue quickly, so I decided to use the straightforward replacement method to save time.

**Comment by PhilippMatthes** [comment]
I now implemented a xml parser, which is still to be tested in the unit tests. It can be used to parse our xml output more easily by using two steps:
1. Filter our result output set by the files we want and return the xml file in a dictionary form
2. Extract the values from the generated dictionary

I am already using it for my Checkstyle implementation, using the following two code lines: 
```
checkstyle_context = parser.context(
            startswith="checkstyle_errors",
            endswith=".xml",
            filter_keys=[]
)
checkstyle_errors = Parser.extract(dictionary=checkstyle_context, key="error")
```

Do you have any improvement suggestions or other concerns about this solution @martinmo? The next step is to implement a nice frontend solution of our checkstyle output. Then I will add pmd and spotbugs support, for which I already created the ant tasks, but they need further improvements and bug fixing first.

**Comment by martinmo** [comment]
@PhilippMatthes it think it's time to open a work-in-progress PR for this, so I can look into it and comment the code directly.

**Comment by PhilippMatthes** [comment]
@martinmo I know that you'd like SpotBugs to run on our system, but I've been trying to implement SpotBugs for a few days now without success. The ant task

```
<property name="spotbugs.home" value="lib/spotbugs-3.1.1"/>
<taskdef resource="edu/umd/cs/findbugs/anttask/tasks.properties" classpath="lib/spotbugs-3.1.1/lib/spotbugs-ant.jar"/>
<target name="spotbugs">
  <spotbugs home="${spotbugs.home}" output="xml" outputFile="${checker.output}/spotbugs_errors.xml">
    <fileset dir="${checker.input}" includes="**/*.java"/>
    <sourcePath path="${checker.input}"/>
  </spotbugs>
</target>
```
produces the following error:
```
[spotbugs] java.io.IOException: IOException while scanning codebases
 [spotbugs] 	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:282)
 [spotbugs] 	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
 [spotbugs] 	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1187)
 [spotbugs] Caused by: edu.umd.cs.findbugs.classfile.ResourceNotFoundException: Resource not found: java/lang/Object.class
 [spotbugs] 	at edu.umd.cs.findbugs.classfile.impl.ClassPathImpl.lookupResource(ClassPathImpl.java:164)
 [spotbugs] 	at edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:282)
 [spotbugs] 	at edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:674)
 [spotbugs] 	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:215)
 [spotbugs] 	... 2 more
```
...which indicates that SpotBugs cannot find or build several Java Classes. It seems like this is a common issue, as referenced by the issues [#148](https://github.com/spotbugs/spotbugs/issues/148), [#365](https://github.com/find-sec-bugs/find-sec-bugs/issues/365) and [#367](https://github.com/find-sec-bugs/find-sec-bugs/issues/367) which were added to the label `bug` on the SpotBugs GitHub repo. **Therefore, I advise that we don't search for a workaround and wait until this issue is fixed. We should not waste any more time investigating this, since CheckStyle and PMD both give us a nice Code Style report.** What do you think about this?
