### ISSUE TITLE
Reject invalid email addresses during registration

### ISSUE THREAD

**Issue by olivergierke** [st-tu-dresden/inloop#167]
I tried to register with my TU Dresden email address `gierke@tu-dresden.de` and got a message saying that I should've received an email to that address which I never received.

While I learned that that particular email address seems to be a special one (usually they contain the first name in the local part), it would've been cool I got an error message that outright told me that I entered an email address invalid to the system.

**Comment by martinmo** [comment]
I agree there's room for improvement here. As a first step I'm going to enable stricter format checks. In addition, the success message displayed after submitting the registration form should probably contain a warning.

There are some caveats which make it impossible to achieve a 100% user-friendly solution:

* The firstname.lastname pattern just seems to be a convention, which is not adhered to all the times. That means if we reject everything else, somebody might not be able to create an account without our help.
* A syntactically correct address doesn't mean the mailbox exists. In order to find out whether the mailbox exists, we have to try to send it and *wait* for the answer of the receiving mail server :( Example: a `Recipient verification error` is returned via email after 30 or more seconds. At this time the user could have already closed his browser and we obviously can't contact him or her.
* If we are unlucky, even mail to an existing mailbox might still not be delivered due to some other errors which will confuse users again.

**Comment by martinmo** [comment]
The signup form now looks like this:
![form](https://cloud.githubusercontent.com/assets/1561982/21057518/4e3b67d8-be3a-11e6-9d28-7de0d0a08d3d.png)

On validation failure:
![formerror](https://cloud.githubusercontent.com/assets/1561982/21057557/7222819a-be3a-11e6-99bb-17f34f800f2a.png)

After successful *form* validation (which only means the email had a correct syntax):
![valid](https://cloud.githubusercontent.com/assets/1561982/21057610/ac34080e-be3a-11e6-9503-dac53b8e2da7.png)

The validation regex, help texts and messages aren't hardcoded anymore and can be changed in the admin interface:
![settings](https://cloud.githubusercontent.com/assets/1561982/21057639/c7d346b0-be3a-11e6-8cac-19a6564bd650.png)

**Comment by olivergierke** [comment]
Thanks, Martin!
