### ISSUE TITLE
Size of testrunner stdout/stderr and files is unlimited

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#199]
Our database is quite large, given that we only store simple text such as JUnit XML reports etc. I analyzed the data and found that we have `TestResult` rows as large as 64 MB (fortunately only once). But there are many more solutions with output sizes above 50 KB (cause no. 1 is infinite recursion).

In addition to the time, CPU and memory limits, there should be a maximum amount of characters (or bytes) in the `TestResult` and `TestOutput` models. Ideally, the amount is configurable in the settings module.

**Comment by martinmo** [comment]
Oh, and I forgot to mention that the solution detail view usually crashes the browser for such large outputs.

**Comment by PhilippMatthes** [comment]
Before we continue on this issue, I feel like we should discuss/brainstorm this further.

I personally see two possible paths we could go:

## 1. Use the db parameter `max_length`
```python
output = models.TextField(max_length=10000)
```
Advantages:
- No further (potentially erroneous) changes on the testrunner are needed.
- TextFields are limited out of the box due to DB-Limits. Changing the limits could be fine, because it was mentioned that there was a stable testoutput with the builtin max row size (64MB).

Disadvantages:
- AFAIK, any changes to model fields such as the change of `max_length` need `pipenv run ./manage.py makemigrations` to be run afterwards.
- Changes to this setting could also destabilize some parts of our system as far as I am concerned. Therefore this issue depends on many tests to further validate that no module is destabilized.
- AFAIK, changes to this setting could truncate existing db entries.

## 2. Limit the TestRunner

We could truncate the TestRunner output to a specific length.

Advantages:
- On running instances, existing TestOutputs definitely stay untouched.
- Changes can be made on-the-fly without database migration afterwards.

Disadvantages:
- Changes are made on a low level and as previously experienced, we could lose time on low level implementation details. Changes could be erroneous.
- Further testing is needed to mitigate potential drawbacks, just like in path 1.

---

Personally, I like path 1 more. Because the needed implementation changes could destabilize our system on both implementation paths and the feature to change this setting on-the-fly isn't necessary IMHO. But I am open to further discussion.

**Comment by martinmo** [comment]
Because of 

> Ideally, the amount is configurable in the settings module.

and in order to limit the output as early as possible in the "pipeline", we should choose option 2.

In Python it is quite easy to cut off a `str` using slicing, i.e.:

```python
some_str = "foobarbaz"
print(some_str[:3])
```

would just print `foo`. There is a problem, however. And I don't know whether we can solve this in plain Python. The `subprocess` module doesn't seem to provide any way to limit the data coming in through the stdout and stderr streams. Our workers could fail with an out-of-memory error even before we have a change to slice off the contents of the captured stdout and stderr streams.

**Comment by PhilippMatthes** [comment]
https://github.com/st-tu-dresden/inloop/blob/53124821e9939c2b60c35968a904a8c0371240a6/inloop/testrunner/runner.py#L151

@martinmo, is there actually any option to limit the output size before it is retrieved by `proc.communicate`? Otherwise, I would just do the following changes and add another test:

```diff
+ limit = self.config.get("pipe_limit", "10000")
+ 
- stderr = stderr.decode("utf-8", errors="replace")
+ stderr = stderr.decode("utf-8", errors="replace")[:limit]
- stdout = stdout.decode("utf-8", errors="replace")
+ stdout = stdout.decode("utf-8", errors="replace")[:limit]
```

Is this then sufficient?

**Comment by martinmo** [comment]
Yep, this should be sufficient, as we cannot do more than this in Python. It might make sense to add an additional layer of defense in the form of a `| head -c $LIMIT` in the docker entrypoint script, once I've merged the stdout and stderr streams into one stream.

**Comment by PhilippMatthes** [comment]
> once I've merged the stdout and stderr streams into one stream.

I suppose you are referring to #236? Then it would make sense to add the "revisit later" badge to this issue.
