### ISSUE TITLE
Add an Implementation of ArchUnit to the ideas and wishlist

### ISSUE THREAD

**Issue by PhilippMatthes** [st-tu-dresden/inloop#226]
As @bdemuth pointed out, ArchUnit could be a possibility to replace or extend our JUnit tests. As part of the tutor team in Softwaretechnology I, we also discussed on how ArchUnit could be a better solution, because it could reduce frustration and improve the learning quality. @bdemuth @phdd  maybe you want to add some more explanation on benefits and drawbacks of ArchUnit, since I have not tested it yet.

**Comment by phdd** [comment]
ArchUnit can replace reflection based architecture testing by adding another layer of abstraction for architecture only. This would lead to a better understanding of the tests among the students.

**Comment by martinmo** [comment]
Thanks for the pointer, this is definitely a good idea and could simplify some of our current asserts. But I think this issue should move to our inloop-tasks repo, because in INLOOP itself we don't need to change anything in order to support this kind of tests (they are JUnit tests, after what I've seen in the examples in https://github.com/TNG/ArchUnit-Examples). This is a matter of (re-) writing our unit tests. I'll close this and will open an issue there instead.

**Comment by PhilippMatthes** [comment]
@martinmo you are right, it would have been placed better over there. Thanks for closing.
