### ISSUE TITLE
Display tasks ordered by pubdate and deadline

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#238]

**Comment by PhilippMatthes** [comment]
@martinmo I found a JavaScript plugin named (tablesort)[https://github.com/tristen/tablesort] which would allow this feature. What do you think about it?

**Comment by martinmo** [comment]
Hmm, I don't really like using Javascript for such a tiny feature. I would prefer sorting at the Django ORM layer instead. Anyway, the user isn't supposed to change the sorting.

**Comment by PhilippMatthes** [comment]
Ok, so I misunderstood this. What I added was an option for the user to click on the table heads and sort everything. So this issue was originally addressing a simple sort operation before the passing-to-template thingy happens. I'll file another PR when this is implemented. Anything left uncleared?

**Comment by martinmo** [comment]
> Anything left uncleared?

I don't think so :-) Sorry for the unclear specification in the first place ;-)

**Comment by PhilippMatthes** [comment]
@martinmo This feature already existed, but I extended it now so it is possible to click on the table head to sort the tasks. For this, the field to sort by is passed as a GET parameter and checked for existence. If existent, the table is returned, sorted by the given field. This solution comes with no JavaScript whatsoever. The filtering is done in the backend, as you requested. What do you think about this solution?
