### ISSUE TITLE
Redis server shouldn't be required for tests

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#297]
PR #282 introduced `redis-server` as Travis service, which shouldn't be necessary because we configured `huey` "eager mode" during tests. Need to investigate why it tries to access a real redis server.

**Comment by PhilippMatthes** [comment]
Let's investigate this further. The `always_eager` flag is set, which is, why tasks should be executed directly after they were executed. However, the `lock_task` decorator uses a context manager, `TaskLock`, which needs the Redis service (called `storage` in the api). The responsible call can be seen here: https://github.com/coleifer/huey/blob/eda3de7402437a6a73223d2439e1c9f9299fb1f0/huey/api.py#L289

## Solution
- Remove `Redis` service from the `.travis.yml` configuration
- Test `create_archive` instead of `create_archive_async`, as the latter is only a wrapper for the already sufficiently tested Huey library
